# Generated by Django 5.2.1 on 2025-07-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_reimbursementclaim_reimbursementfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementclaim',
            name='approve_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursementfile',
            name='file',
            field=models.FileField(upload_to='bills/'),
        ),
    ]
