# Generated by Django 5.2.1 on 2025-07-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_alter_reimbursementclaim_approve_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementfile',
            name='file',
            field=models.FileField(upload_to='reimbursements'),
        ),
    ]
