# Generated by Django 5.2.1 on 2025-07-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_alter_reimbursementfile_file'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='reimbursementclaim',
            name='approve_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursementclaim',
            name='submitted_at',
            field=models.DateTimeField(),
        ),
    ]
