# Generated by Django 5.2.1 on 2025-08-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementclaim',
            name='file',
            field=models.FileField(default=1, upload_to='reimbusements'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reimbursementclaim',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='ReimbursementFile',
        ),
    ]
